version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=twitterpass
      - MYSQL_DATABASE=twitter
    ports:
      - 3306:3306

  data_collect:
    image: node:12.13
    working_dir: /home/node/app
    volumes:
      - ./twitter_collect:/home/node/app
    links:
      - db
    command: bash -c 'npm install && npm start'

  api:
    image: adoptopenjdk/maven-openjdk11
    links:
      - db
    working_dir: /workspace
    volumes:
      - ./api:/workspace
    ports:
      - 8080:8080
    command: bash -c 'mvn package && java -jar target/testitau-1.0.0.jar'

  front:
    image: 'node:11'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .front/:/home/node/app
    ports:
      - '3000:3000'
    command: bash -c "yarn && yarn start"
